### ISSUE TITLE
Fix potential security vulnerability

### ISSUE THREAD

**Issue by eric-ls** [calblueprint/sjc#40]
we should address the security vulnerability that github is warning us about. Looks like we have to update the `paperclip` gem

<img width="1007" alt="screen shot 2018-02-09 at 4 02 42 pm" src="https://user-images.githubusercontent.com/8058313/36055661-befd56fc-0db2-11e8-8623-1d0a24570e1e.png">

**Comment by amyshan** [comment]
fixed!
